// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: LCD_0415

#include "../ui.h"

void ui_Screen_Init_screen_init(void)
{
    ui_Screen_Init = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Init, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_Init, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Init, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen_Init);
    lv_obj_set_width(ui_Panel6, 100);
    lv_obj_set_height(ui_Panel6, 50);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "正在初始化...");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

}
