// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: LCD_0415

#include "../ui.h"

void ui_Screen_menu_screen_init(void)
{
    ui_Screen_menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button_Red = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_Red, 60);
    lv_obj_set_height(ui_Button_Red, 40);
    lv_obj_set_x(ui_Button_Red, 7);
    lv_obj_set_y(ui_Button_Red, 56);
    lv_obj_add_flag(ui_Button_Red, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Red, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Button_Red);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "红色");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Blue = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_Blue, 60);
    lv_obj_set_height(ui_Button_Blue, 40);
    lv_obj_set_x(ui_Button_Blue, 138);
    lv_obj_set_y(ui_Button_Blue, 56);
    lv_obj_add_flag(ui_Button_Blue, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Blue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button_Blue);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "蓝色");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Meteor = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_Meteor, 60);
    lv_obj_set_height(ui_Button_Meteor, 40);
    lv_obj_set_x(ui_Button_Meteor, 72);
    lv_obj_set_y(ui_Button_Meteor, 105);
    lv_obj_add_flag(ui_Button_Meteor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Meteor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button_Meteor);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "流星");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Yellow = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_Yellow, 60);
    lv_obj_set_height(ui_Button_Yellow, 40);
    lv_obj_set_x(ui_Button_Yellow, 73);
    lv_obj_set_y(ui_Button_Yellow, 56);
    lv_obj_add_flag(ui_Button_Yellow, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Yellow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button_Yellow);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "黄色");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Fire = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_Fire, 60);
    lv_obj_set_height(ui_Button_Fire, 40);
    lv_obj_set_x(ui_Button_Fire, 8);
    lv_obj_set_y(ui_Button_Fire, 104);
    lv_obj_add_flag(ui_Button_Fire, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Fire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Button_Fire);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "火焰");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_RainBow = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_RainBow, 60);
    lv_obj_set_height(ui_Button_RainBow, 40);
    lv_obj_set_x(ui_Button_RainBow, 139);
    lv_obj_set_y(ui_Button_RainBow, 105);
    lv_obj_add_flag(ui_Button_RainBow, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_RainBow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Button_RainBow);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "彩虹");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Screen_menu);
    lv_slider_set_value(ui_Slider1, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 209);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -47);
    lv_obj_set_y(ui_Slider1, 101);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_Button_Audio = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_Audio, 60);
    lv_obj_set_height(ui_Button_Audio, 40);
    lv_obj_set_x(ui_Button_Audio, 8);
    lv_obj_set_y(ui_Button_Audio, 153);
    lv_obj_add_flag(ui_Button_Audio, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Audio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button_Audio);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "音频");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_White = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_White, 60);
    lv_obj_set_height(ui_Button_White, 40);
    lv_obj_set_x(ui_Button_White, 73);
    lv_obj_set_y(ui_Button_White, 153);
    lv_obj_add_flag(ui_Button_White, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_White, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Button_White);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "白光");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Off = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_Off, 60);
    lv_obj_set_height(ui_Button_Off, 40);
    lv_obj_set_x(ui_Button_Off, 139);
    lv_obj_set_y(ui_Button_Off, 153);
    lv_obj_add_flag(ui_Button_Off, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Off, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Button_Off);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "关闭");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_brightness = lv_label_create(ui_Screen_menu);
    lv_obj_set_width(ui_Label_brightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_brightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_brightness, 135);
    lv_obj_set_y(ui_Label_brightness, 103);
    lv_obj_set_align(ui_Label_brightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_brightness, "100%");
    lv_obj_set_style_text_font(ui_Label_brightness, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Connect_Onenet = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_Connect_Onenet, 57);
    lv_obj_set_height(ui_Button_Connect_Onenet, 30);
    lv_obj_set_x(ui_Button_Connect_Onenet, 243);
    lv_obj_set_y(ui_Button_Connect_Onenet, 30);
    lv_obj_add_flag(ui_Button_Connect_Onenet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Connect_Onenet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Onenet_Status = lv_label_create(ui_Button_Connect_Onenet);
    lv_obj_set_width(ui_Label_Onenet_Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Onenet_Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Onenet_Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Onenet_Status, " 未连接 ");
    lv_obj_set_style_text_font(ui_Label_Onenet_Status, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button_Connect_Bluetooth = lv_btn_create(ui_Screen_menu);
    lv_obj_set_width(ui_Button_Connect_Bluetooth, 58);
    lv_obj_set_height(ui_Button_Connect_Bluetooth, 29);
    lv_obj_set_x(ui_Button_Connect_Bluetooth, 242);
    lv_obj_set_y(ui_Button_Connect_Bluetooth, 99);
    lv_obj_add_flag(ui_Button_Connect_Bluetooth, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_Connect_Bluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_Bluetooth_Status = lv_label_create(ui_Button_Connect_Bluetooth);
    lv_obj_set_width(ui_Label_Bluetooth_Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Bluetooth_Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_Bluetooth_Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Bluetooth_Status, " 未连接 ");
    lv_obj_set_style_text_font(ui_Label_Bluetooth_Status, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_ShowMSG = lv_obj_create(ui_Screen_menu);
    lv_obj_set_width(ui_Panel_ShowMSG, 320);
    lv_obj_set_height(ui_Panel_ShowMSG, 240);
    lv_obj_set_align(ui_Panel_ShowMSG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel_ShowMSG, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel_ShowMSG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_ShowMSG, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_ShowMSG, 128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel_ShowMSG);
    lv_obj_set_width(ui_Panel2, 130);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMSG = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelMSG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMSG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMSG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMSG, " 这是Label占位符 ");
    lv_obj_set_style_text_font(ui_LabelMSG, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen_menu);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 93);
    lv_obj_set_y(ui_Label7, 102);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "亮度:");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen_menu);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -120);
    lv_obj_set_y(ui_Label14, -105);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "当前时间:");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_time = lv_label_create(ui_Screen_menu);
    lv_obj_set_width(ui_Label_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_time, -26);
    lv_obj_set_y(ui_Label_time, -104);
    lv_obj_set_align(ui_Label_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_time, "2020-10-10 12:00");
    lv_obj_set_style_text_font(ui_Label_time, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Screen_menu);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 112);
    lv_obj_set_y(ui_Label19, -104);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "连接网络");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Screen_menu);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 113);
    lv_obj_set_y(ui_Label20, -40);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "连接蓝牙");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Screen_menu);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 112);
    lv_obj_set_y(ui_Label21, 31);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "当前模式");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_led_mode = lv_label_create(ui_Screen_menu);
    lv_obj_set_width(ui_Label_led_mode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_led_mode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_led_mode, 109);
    lv_obj_set_y(ui_Label_led_mode, 60);
    lv_obj_set_align(ui_Label_led_mode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_led_mode, "关闭");
    lv_obj_set_style_text_font(ui_Label_led_mode, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button_Red, ui_event_Button_Red, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Blue, ui_event_Button_Blue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Meteor, ui_event_Button_Meteor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Yellow, ui_event_Button_Yellow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Fire, ui_event_Button_Fire, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_RainBow, ui_event_Button_RainBow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Audio, ui_event_Button_Audio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_White, ui_event_Button_White, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Off, ui_event_Button_Off, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Connect_Onenet, ui_event_Button_Connect_Onenet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button_Connect_Bluetooth, ui_event_Button_Connect_Bluetooth, LV_EVENT_ALL, NULL);

}
