// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: LCD_0415

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen_Init
void ui_Screen_Init_screen_init(void);
lv_obj_t * ui_Screen_Init;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label18;


// SCREEN: ui_Screen_menu
void ui_Screen_menu_screen_init(void);
lv_obj_t * ui_Screen_menu;
void ui_event_Button_Red(lv_event_t * e);
lv_obj_t * ui_Button_Red;
lv_obj_t * ui_Label1;
void ui_event_Button_Blue(lv_event_t * e);
lv_obj_t * ui_Button_Blue;
lv_obj_t * ui_Label2;
void ui_event_Button_Meteor(lv_event_t * e);
lv_obj_t * ui_Button_Meteor;
lv_obj_t * ui_Label3;
void ui_event_Button_Yellow(lv_event_t * e);
lv_obj_t * ui_Button_Yellow;
lv_obj_t * ui_Label4;
void ui_event_Button_Fire(lv_event_t * e);
lv_obj_t * ui_Button_Fire;
lv_obj_t * ui_Label5;
void ui_event_Button_RainBow(lv_event_t * e);
lv_obj_t * ui_Button_RainBow;
lv_obj_t * ui_Label6;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
void ui_event_Button_Audio(lv_event_t * e);
lv_obj_t * ui_Button_Audio;
lv_obj_t * ui_Label8;
void ui_event_Button_White(lv_event_t * e);
lv_obj_t * ui_Button_White;
lv_obj_t * ui_Label9;
void ui_event_Button_Off(lv_event_t * e);
lv_obj_t * ui_Button_Off;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label_brightness;
void ui_event_Button_Connect_Onenet(lv_event_t * e);
lv_obj_t * ui_Button_Connect_Onenet;
lv_obj_t * ui_Label_Onenet_Status;
void ui_event_Button_Connect_Bluetooth(lv_event_t * e);
lv_obj_t * ui_Button_Connect_Bluetooth;
lv_obj_t * ui_Label_Bluetooth_Status;
lv_obj_t * ui_Panel_ShowMSG;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_LabelMSG;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label_time;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label_led_mode;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button_Red(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_Red(e);
    }
}
void ui_event_Button_Blue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_Blue(e);
    }
}
void ui_event_Button_Meteor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_Metor(e);
    }
}
void ui_event_Button_Yellow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_Yellow(e);
    }
}
void ui_event_Button_Fire(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_Fire(e);
    }
}
void ui_event_Button_RainBow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_RainBow(e);
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        ui_event_Silder(e);
    }
}
void ui_event_Button_Audio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_Audio(e);
    }
}
void ui_event_Button_White(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_White(e);
    }
}
void ui_event_Button_Off(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_Off(e);
    }
}
void ui_event_Button_Connect_Onenet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_Connect_Onenet(e);
    }
}
void ui_event_Button_Connect_Bluetooth(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_event_click_Connect_Bluetooth(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen_Init_screen_init();
    ui_Screen_menu_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen_Init);
}
