// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: LCD_0415

#ifndef _LCD_0415_UI_H
#define _LCD_0415_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label_brightness;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label11;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel_Connected_Bluetooth;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel_Disonnected_Bluetooth;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel_Connected_Net;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel_Disconnected_Net;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label_time;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
