// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: LCD_0415

#ifndef _LCD_0415_UI_H
#define _LCD_0415_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen_Init
void ui_Screen_Init_screen_init(void);
extern lv_obj_t * ui_Screen_Init;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label18;
// SCREEN: ui_Screen_menu
void ui_Screen_menu_screen_init(void);
extern lv_obj_t * ui_Screen_menu;
void ui_event_Button_Red(lv_event_t * e);
extern lv_obj_t * ui_Button_Red;
extern lv_obj_t * ui_Label1;
void ui_event_Button_Blue(lv_event_t * e);
extern lv_obj_t * ui_Button_Blue;
extern lv_obj_t * ui_Label2;
void ui_event_Button_Meteor(lv_event_t * e);
extern lv_obj_t * ui_Button_Meteor;
extern lv_obj_t * ui_Label3;
void ui_event_Button_Yellow(lv_event_t * e);
extern lv_obj_t * ui_Button_Yellow;
extern lv_obj_t * ui_Label4;
void ui_event_Button_Fire(lv_event_t * e);
extern lv_obj_t * ui_Button_Fire;
extern lv_obj_t * ui_Label5;
void ui_event_Button_RainBow(lv_event_t * e);
extern lv_obj_t * ui_Button_RainBow;
extern lv_obj_t * ui_Label6;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
void ui_event_Button_Audio(lv_event_t * e);
extern lv_obj_t * ui_Button_Audio;
extern lv_obj_t * ui_Label8;
void ui_event_Button_White(lv_event_t * e);
extern lv_obj_t * ui_Button_White;
extern lv_obj_t * ui_Label9;
void ui_event_Button_Off(lv_event_t * e);
extern lv_obj_t * ui_Button_Off;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label_brightness;
void ui_event_Button_Connect_Onenet(lv_event_t * e);
extern lv_obj_t * ui_Button_Connect_Onenet;
extern lv_obj_t * ui_Label_Onenet_Status;
void ui_event_Button_Connect_Bluetooth(lv_event_t * e);
extern lv_obj_t * ui_Button_Connect_Bluetooth;
extern lv_obj_t * ui_Label_Bluetooth_Status;
extern lv_obj_t * ui_Panel_ShowMSG;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_LabelMSG;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label_time;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label_led_mode;
extern lv_obj_t * ui____initial_actions0;





LV_FONT_DECLARE(ui_font_Font1);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
