// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: LCD_0415

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_click_Red(lv_event_t * e);
void ui_event_click_Blue(lv_event_t * e);
void ui_event_click_Metor(lv_event_t * e);
void ui_event_click_Yellow(lv_event_t * e);
void ui_event_click_Fire(lv_event_t * e);
void ui_event_click_RainBow(lv_event_t * e);
void ui_event_Silder(lv_event_t * e);
void ui_event_click_Audio(lv_event_t * e);
void ui_event_click_White(lv_event_t * e);
void ui_event_click_Off(lv_event_t * e);
void ui_event_click_Connect_Bluetooth(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
